# <center> Introduction to Python </center>
## <center> [For more information, check the link here.](https://www.py4e.com/lessons) </center>




## Agenda 

- Constants and Variables
- Types of variables
- Conditional statement
- Debugging codes
- Data collection and presentation


## 1- Constants:

Fixed values that can not be changed such as numbers or letters.

#### example: 

print(54) <br>
print('Hello Class!') <br>





In [1]:
print(54) 
print('Hello Class!') 

54
Hello Class!


## 2- Variables:

Named places in the memory where a programmer can store data and later retrieve them (with the variable name).

#### example: 

A= 14 <br>
B= 29 <br>
A= 32 <br>
<br>
A=?

In [3]:
A= 14 
B= 29 
A= 32 

A

32

## 3- Numerical Expressions

* Addition     +
* Subtraction  -
* Multiplication *
* Division /
* Power **
* Remainder %

In [1]:
23 % 7

2

## 4- Types of Variables and Constants

* int
* str
* float

### example:

* type('Hamilton')=?
* type(53)=?
* type(53.2)=?


In [9]:
type(53)

int

## 5- Conditional Execution

* Less than <
* Less than or equal to <=
* Greater than >
* Greater than or equal to >=
* Equal to ==
* Not Equal to !=


In [21]:
x=35

if x == 35:
    print('It was equal ...')

if x < 100:
        print('It was less than ...')
    
    

It was equal ...
It was less than ...


In [8]:
y= 25

if y<=20:
    print('First condition ...')
    
elif y < 30:
        print('Second condition ...')
        
else:
    print('Third condition ...')

Second condition ...


## 6- Debugging codes with "Try/Except"

* If the code in "try" works, the "except" section is skipped.
* If the code in the try fails, it jumps to the "except" section.

In [9]:
A='12'   # you can use single quote or double quote 

type(A)

str

In [12]:
float(A)

12.0

In [13]:
Book = 'Hello Bob'
Pen = int(Book)
print('First', Book)




ValueError: invalid literal for int() with base 10: 'Hello Bob'

In [16]:
try:
    Book = 'Hello Bob'
    Pen = int(hello)
    print('First', Book)
    
except:
    print('Program continued but you should check the first part ...')

A='Class'

print(A)
    
    

Program continued but you should check the first part ...
Class


## 7- Lists [[Ref]](https://www.py4e.com/lessons/lists)

* List constants are separated by commas and surrounded by square brackets.
* List can have any python object even another list
* Lists are mutable 


In [17]:
A=[(2,3),[4,5],9]

type(A)

list

In [20]:
type(A[0])   #List can have any python object even another list

tuple

In [21]:
A[2]='Book'     #Lists are mutable
A

[(2, 3), [4, 5], 'Book']

In [22]:
B='Pen'

In [23]:
B[1]

'e'

In [19]:
B[1]='C'  #Strings are not mutable

NameError: name 'B' is not defined

#### Question: What will be the output of List1 + List2?

#### zip() function

In [44]:
l1 = [1, 2, 9]
l2 = [4, 'B', 9]

list(zip(l1,l2))    

[(1, 4), (2, 'B'), (9, 9)]

## 8- Tuples [[Ref]](https://www.py4e.com/lessons/tuples)

Tuples are not mutable (similar to strings but unlike to lists).

In [29]:
B=(2,3,[4,5],9)

In [30]:
B[2]

[4, 5]

In [31]:
B[2]='Book'

TypeError: 'tuple' object does not support item assignment

## 9- Dictionaries [[Ref]](https://www.py4e.com/lessons/dictionary)

- Powerful data collection in Python
- Dictionaries can do fast database-like operations in Python

In [33]:
Uni={'Book':36, 16:4 , 'Name': ['Dave',56,(39,87,5)] , 3:'winner'
}

Uni

{'Book': 36, 16: 4, 'Name': ['Dave', 56, (39, 87, 5)], 3: 'winner'}

In [35]:
Uni[16]

4

In [15]:
Uni[3]

'halk'

In [16]:
type(Uni)

dict

## 10- Commonly used libraries in Python:

![PYlib](Figs/libraries.PNG)

## 11- Data presentation in Numpy [[Ref]](https://docs.scipy.org/doc/numpy/user/quickstart.html)
* np.array
* ndarray.shape
* ndarray.dtype

In [47]:
import numpy as np
k=[[2,3,9],[3,1,6]]
b=np.array(k)
b

array([[2, 3, 9],
       [3, 1, 6]])

In [45]:
b.shape

(2, 3)

In [32]:
b[0,:]

array([2, 3, 9])

In [49]:
B=np.arange(36)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [53]:
C=B.reshape(9,4)   # try reshape(2,3,2,3)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [54]:
C.shape

(9, 4)

#### Dimensions in numpy arrays:

![Numpy array dimensions](Figs/Dim.PNG)

In [51]:
C[:,:,1,0]

array([[ 3,  9, 15],
       [21, 27, 33]])

## 12- Data presentation in Pandas (dataframe) [[Ref]](https://pandas.pydata.org/pandas-docs/stable/10min.html)
* pd.Series()
* pd.DataFrame()
* df.head()
* df.describe()
* df.info()
* df.dtypes
* df.shape
* df.columns
* df.values
* df.T

In [3]:
import pandas as pd
import numpy as np

#### Creating a Series by passing a list of values:

In [61]:
k = pd.Series([8,5,np.nan,10,2])

k

0     8.0
1     5.0
2     NaN
3    10.0
4     2.0
dtype: float64

In [62]:
type(k)

pandas.core.series.Series

#### Creating DataFrame from dictionary 

In [87]:
df = pd.DataFrame({'A' : 1.,
                    'C' : pd.Series(list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })
df

A    C  D      E    F
0  1.0  0.0  3   test  foo
1  1.0  1.0  3  train  foo
2  1.0  2.0  3   test  foo
3  1.0  3.0  3  train  foo

#### Question: What is the type of "one column" in a dataframe?

In [88]:
type(df['A'])

pandas.core.series.Series

#### Converting dataframe to numpy array

In [89]:
A=df.values

A

array([[1.0, 0.0, 3, 'test', 'foo'],
       [1.0, 1.0, 3, 'train', 'foo'],
       [1.0, 2.0, 3, 'test', 'foo'],
       [1.0, 3.0, 3, 'train', 'foo']], dtype=object)

#### Importing data to a dataframe


![dataloading](Figs/DataImport.PNG)

##### 1- From files [(To learn more, click here)](https://www.py4e.com/lessons/files)
##### 2- From database [(To learn more, click here)](https://www.py4e.com/lessons/json)
##### 3- From Internet [(To learn more, click here).](https://www.py4e.com/lessons/servces) For more datasets [(Click here)](https://archive.ics.uci.edu/ml/datasets.html)


In [90]:
import pandas as pd
import numpy as np

df=pd.read_table('C:\\Users\\Esmal\\OneDrive\\CIRC\\Data Science\\GitPushes\\bigdata\\data\\Adult.data',sep=',', header=None)

DFw=pd.read_table('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', sep=',')


In [91]:
DFf.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

#### Visualizing DataFrame

In [105]:
df.describe()

1st           3rd           4th           4th           4th  \
count  32561.000000  3.256100e+04  32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05     10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05      2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04      1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05      9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05     10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05     12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06     16.000000  99999.000000   4356.000000   

                4th  
count  32561.000000  
mean      40.437456  
std       12.347429  
min        1.000000  
25%       40.000000  
50%       40.000000  
75%       45.000000  
max       99.000000

In [106]:
df.info()  # Basic information about the datframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
1st    32561 non-null int64
2nd    32561 non-null object
3rd    32561 non-null int64
4th    32561 non-null object
4th    32561 non-null int64
4th    32561 non-null object
4th    32561 non-null object
4th    32561 non-null object
4th    32561 non-null object
4th    32561 non-null object
4th    32561 non-null int64
4th    32561 non-null int64
4th    32561 non-null int64
4th    32561 non-null object
4th    32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [107]:
df.dtypes

1st     int64
2nd    object
3rd     int64
4th    object
4th     int64
4th    object
4th    object
4th    object
4th    object
4th    object
4th     int64
4th     int64
4th     int64
4th    object
4th    object
dtype: object

In [108]:
df.shape

(32561, 15)

In [109]:
df.columns     # Try df.columns=['1st','2nd','3rd','4th','4th','4th','4th','4th','4th','4th','4th','4th','4th','4th','4th']

Index(['1st', '2nd', '3rd', '4th', '4th', '4th', '4th', '4th', '4th', '4th',
       '4th', '4th', '4th', '4th', '4th'],
      dtype='object')

In [110]:
df.T

0                    1                   2      \
1st              39                   50                  38   
2nd       State-gov     Self-emp-not-inc             Private   
3rd           77516                83311              215646   
4th       Bachelors            Bachelors             HS-grad   
4th              13                   13                   9   
4th   Never-married   Married-civ-spouse            Divorced   
4th    Adm-clerical      Exec-managerial   Handlers-cleaners   
4th   Not-in-family              Husband       Not-in-family   
4th           White                White               White   
4th            Male                 Male                Male   
4th            2174                    0                   0   
4th               0                    0                   0   
4th              40                   13                  40   
4th   United-States        United-States       United-States   
4th           <=50K                <=50K               <=50K   

                   3                    4                    5      \
1st                   53                   28                   37   
2nd              Private              Private              Private   
3rd               234721               338409               284582   
4th                 11th            Bachelors              Masters   
4th                    7                   13                   14   
4th   Married-civ-spouse   Married-civ-spouse   Married-civ-spouse   
4th    Handlers-cleaners       Prof-specialty      Exec-managerial   
4th              Husband                 Wife                 Wife   
4th                Black                Black                White   
4th                 Male               Female               Female   
4th                    0                    0                    0   
4th                    0                    0                    0   
4th                   40                   40                   40   
4th        United-States                 Cuba        United-States   
4th                <=50K                <=50K                <=50K   

                      6                    7                8      \
1st                      49                   52               31   
2nd                 Private     Self-emp-not-inc          Private   
3rd                  160187               209642            45781   
4th                     9th              HS-grad          Masters   
4th                       5                    9               14   
4th   Married-spouse-absent   Married-civ-spouse    Never-married   
4th           Other-service      Exec-managerial   Prof-specialty   
4th           Not-in-family              Husband    Not-in-family   
4th                   Black                White            White   
4th                  Female                 Male           Female   
4th                       0                    0            14084   
4th                       0                    0                0   
4th                      16                   45               50   
4th                 Jamaica        United-States    United-States   
4th                   <=50K                 >50K             >50K   

                   9             ...                         32551  \
1st                   42         ...                            32   
2nd              Private         ...                       Private   
3rd               159449         ...                         34066   
4th            Bachelors         ...                          10th   
4th                   13         ...                             6   
4th   Married-civ-spouse         ...            Married-civ-spouse   
4th      Exec-managerial         ...             Handlers-cleaners   
4th              Husband         ...                       Husband   
4th                White         ...            Amer-Indian-Eskimo   
4th                 Male         ...                          M